apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: todolist-listener
  namespace: giveaway-ci
spec:
  serviceAccountName: tekton-sa
  triggers:
    - triggerRef: todolist-trigger