apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: todolist-template
  namespace: giveaway-ci
spec:
  params:
    - name: git-repo-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-run-
        namespace: giveaway-ci
      spec:
        params:
          - name: repo-url
            value: $(tt.params.git-repo-url)
          - name: revision
            value: $(tt.params.git-revision)
        pipelineRef:
          name: todolist-pipeline
        serviceAccountName: tekton-sa
        workspaces:
          - name: shared-data
            persistentVolumeClaim:
              claimName: tekton-shared-pvc