apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: todolist-binding
  namespace: giveaway
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.head_commit.id)